baseURL = "https://sma-glen.com/" # Replace with your actual domain
languageCode = "en-gb"
title = "Sma' Glen | Specialist Clinical Psychology"

theme = "PaperMod"
disableKinds = ["RSS"]

[params]
    defaultTheme = "auto" # or dark, light
    ShowShareButtons = false
    ShowReadingTime = false
    ShowPostNavLinks = false
    ShowBreadCrumbs = false
    ShowCodeCopyButtons = false

    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 10

[author]
    name = "Joe Hickey"